name: Purge jsDelivr Cache

on:
  push:
    branches:
      - main  # Triggers the purge only when code is pushed to the main branch
    paths:
      - 'js/mgr/**'   # Triggers only if a JS file changes
      - 'css/mgr/**'  # Triggers only if a CSS file changes

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Flush jsDelivr Assets
        run: |
          # Define your configuration vars
          USER="DKworkspaces"
          REPO="Xocu"
          BRANCH="main" 
          # Define your specific folder paths here
          JS_FOLDER="js/mgr"
          CSS_FOLDER="css/mgr"
          
          
          
          
          echo -e "\nAll cache purge requests processed!"
